#!/bin/bash
# sync-packages.sh - Sync installed packages from Nyx to provisioning
#
# Compares manually installed packages on Nyx with config/nyx-packages.txt
# and shows differences. Use --update to overwrite the config file.
#
# Usage:
#   ./sync-packages.sh              # Show diff
#   ./sync-packages.sh --update     # Update provisioning config
#
# Run regularly to keep provisioning up-to-date with actual server state.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
PACKAGES_FILE="$REPO_DIR/config/nyx-packages.txt"
NYX_HOST="fx@100.64.138.99"
SSH_KEY="$HOME/.ssh/id_nyx"

# Packages to ignore (system/default packages that come with Ubuntu)
IGNORE_PATTERNS="^lib|^python3-|linux-|ubuntu-|grub-|snap|^cloud-|^openssh|^ca-certificates"

# ============================================
# Helpers
# ============================================

log() {
    echo "[$(date '+%H:%M:%S')] $1"
}

log_error() {
    echo "[ERROR] $1" >&2
}

# Get manually installed packages from Nyx (excluding system/default packages)
get_nyx_packages() {
    local ssh_opts="-o StrictHostKeyChecking=accept-new -o BatchMode=yes"

    if [[ -f "$SSH_KEY" ]]; then
        ssh_opts+=" -i $SSH_KEY"
    fi

    # shellcheck disable=SC2086
    ssh $ssh_opts "$NYX_HOST" \
        "apt-mark showmanual | grep -vE '$IGNORE_PATTERNS' | sort" 2>/dev/null
}

# Get packages from provisioning config (ignoring comments and blank lines)
get_provisioned_packages() {
    if [[ -f "$PACKAGES_FILE" ]]; then
        grep -vE '^\s*#|^\s*$' "$PACKAGES_FILE" | sort
    else
        echo ""
    fi
}

# ============================================
# Main
# ============================================

usage() {
    cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Sync installed packages from Nyx server to provisioning config.

OPTIONS:
    --update    Update config/nyx-packages.txt with packages from Nyx
    -h, --help  Show this help

EXAMPLES:
    $(basename "$0")           # Show differences
    $(basename "$0") --update  # Overwrite config with Nyx packages
EOF
}

main() {
    local update_mode=0

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --update)
                update_mode=1
                shift
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                usage
                exit 1
                ;;
        esac
    done

    log "Fetching packages from Nyx..."

    # Get packages from both sources
    local nyx_packages provisioned_packages
    nyx_packages=$(get_nyx_packages)
    provisioned_packages=$(get_provisioned_packages)

    if [[ -z "$nyx_packages" ]]; then
        log_error "Failed to get packages from Nyx. Is SSH configured?"
        exit 1
    fi

    if [[ $update_mode -eq 1 ]]; then
        log "Updating $PACKAGES_FILE..."

        # Write header and packages
        cat > "$PACKAGES_FILE" <<EOF
# nyx-packages.txt - Packages to install on Nyx server
# Auto-generated by sync-packages.sh on $(date '+%Y-%m-%d')
# Manual edits will be preserved if you add comments

EOF
        echo "$nyx_packages" >> "$PACKAGES_FILE"

        local count
        count=$(echo "$nyx_packages" | wc -l | tr -d ' ')
        log "Updated with $count packages"

    else
        echo ""
        echo "=== Packages on Nyx but not in provisioning ==="
        comm -23 <(echo "$nyx_packages") <(echo "$provisioned_packages") || echo "(none)"
        echo ""
        echo "=== Packages in provisioning but not on Nyx ==="
        comm -13 <(echo "$nyx_packages") <(echo "$provisioned_packages") || echo "(none)"
        echo ""
        echo "Run with --update to sync from Nyx"
    fi
}

main "$@"
